<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
<<<<<<< HEAD
  <suite started-at="2021-10-19T14:37:09 IST" name="Default suite" finished-at="2021-10-19T14:37:41 IST" duration-ms="31946">
    <groups>
    </groups>
    <test started-at="2021-10-19T14:37:09 IST" name="Default test" finished-at="2021-10-19T14:37:41 IST" duration-ms="31946">
      <class name="com.eagle.TestCases.InvestigationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.eagle.TestCases.InvestigationTest@3232a28a]" started-at="2021-10-19T14:37:09 IST" name="launchApplication" finished-at="2021-10-19T14:37:16 IST" duration-ms="6378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="test_CreateInvestigation_Correct()[pri:0, instance:com.eagle.TestCases.InvestigationTest@3232a28a]" started-at="2021-10-19T14:37:16 IST" name="test_CreateInvestigation_Correct" finished-at="2021-10-19T14:37:41 IST" duration-ms="25521" status="PASS">
=======
  <suite started-at="2021-10-19T13:41:58 IST" name="Default suite" finished-at="2021-10-19T13:43:38 IST" duration-ms="99290">
    <groups>
    </groups>
    <test started-at="2021-10-19T13:41:58 IST" name="Default test" finished-at="2021-10-19T13:43:38 IST" duration-ms="99290">
      <class name="com.eagle.TestCases.SetTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.eagle.TestCases.SetTest@3b6ddd1d]" started-at="2021-10-19T13:41:58 IST" name="launchApplication" finished-at="2021-10-19T13:42:06 IST" duration-ms="7369" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="test_Set_Correct()[pri:0, instance:com.eagle.TestCases.SetTest@3b6ddd1d]" started-at="2021-10-19T13:42:06 IST" name="test_Set_Correct" finished-at="2021-10-19T13:43:38 IST" duration-ms="91869" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Disease] but found [Set Test Auto 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Disease] but found [Set Test Auto 1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.eagle.pages.Page.verifyPage(Page.java:53)
at com.eagle.pages.SetPage.ExpandAddFromCatalog(SetPage.java:426)
at com.eagle.TestCases.SetTest.test_Set_Correct(SetTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
>>>>>>> 19e074445253508a5d7731108039f72c37045659
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_CreateInvestigation_Correct -->
      </class> <!-- com.eagle.TestCases.InvestigationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
